name: Deploy hugo site to Github Pages

on:
  # runs on pushes to the default branch.
  push:
    branches:
      - main

  # allow to run workflow manually from Actions tab.
  workflow_dispatch:

# sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# only allow one concurrent deployment.
concurrency:
  group: "pages"
  cancel-in-progress: false

# default shell is bash (maybe consider something later...)
defaults:
  run: 
    shell: bash

jobs:
  build: 

    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Install the Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
    
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout code
        uses: actions/checkout@v4
        with:
         submodules: recursive
         fetch-depth: 0.128
    
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Node JS
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      
      - name: Hugo Build
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: America/New_York
        run: |
          hugo \
              --gc \
             --minify \
             --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact/@v3
        with:
          path: ./public
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@4


  





